export enum CourseControlActionTypes {
    CREATE_CATEGORY_FORM_CHANGE = "course/CREATE_CATEGORY_FORM_CHANGE",
    CREATE_CATEGORY_FORM_CLEAR = "course/CREATE_CATEGORY_FORM_CLEAR",
    CREATE_COURSE_FORM_CHANGE = "course/CREATE_COURSE_FORM_CHANGE",
    CREATE_COURSE_FORM_CLEAR = "course/CREATE_COURSE_FORM_CLEAR",
    SET_ACTIVE_COURSE = "course/SET_ACTIVE_COURSE",
    SELECT_GRADE_CATEGORY = "course/SELECT_GRADE_CATEGORY",
}
