version: '3.7'

services: 
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: grade-tracker-backend
    container_name: grade-tracker-backend
    volumes: 
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports: 
      - "8000:8000"
    depends_on: 
      - mongo
    env_file: ./backend/.env
    environment: 
      - NODE_ENV=production
    networks: 
      - grade-tracker
  
  mongo:
    image: mongo
    container_name: grade-tracker-mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - grade-tracker
  
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: grade-tracker-frontend
    container_name: grade-tracker-frontend
    volumes: 
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    ports: 
      - "80:80"
    depends_on: 
      - mongo
    env_file: ./frontend/.env
    environment: 
      - NODE_ENV=production
    networks: 
      - grade-tracker

networks:
  grade-tracker:
    driver: bridge

volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local